apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsdb-frontend
  namespace: rsdb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: rsdb-frontend
  template:
    metadata:
      labels:
        app: rsdb-frontend
    spec:
      containers:
      - name: rsdb-frontend-container
        image: webstradev/rsdb-frontend:latest 
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
